# Generated by Django 4.1.8 on 2023-04-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexpage",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
