# Generated by Django 4.1.8 on 2023-05-03 07:21

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("flex", "0002_flexpage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexpage",
            name="specification_URL",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="flexpage",
            name="description",
            field=wagtail.fields.RichTextField(default=""),
        ),
    ]
