# Generated by Django 4.1.8 on 2023-05-03 07:28

from django.db import migrations
import flex.models


class Migration(migrations.Migration):
    dependencies = [
        ("flex", "0003_flexpage_specification_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="specification_URL",
            field=flex.models.CustomRichTextField(),
        ),
    ]
