# Generated by Django 4.1.8 on 2023-05-03 07:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("flex", "0004_alter_flexpage_specification_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexpage",
            name="accordion_items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "accordion_item",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(required=True),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=None,
            ),
        ),
    ]
